### ISSUE TITLE
Duplicate hole names, which to choose?

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.StructuredEvents#46]
`logger.Info("{Name} {Name}", "a", "b");

Should be the name "a" or "b"? (first or last occurrence. 

Compatibility with Serilog would be preferred  -so we have to check that one.

**Comment by nblumhardt** [comment]
Serilog (counter-intuitively) selects the _second_ argument, so `Name` will  `"b"` in this case. I think the choice was just an optimisation to avoid checking for existence of each property on add, IIRC, and not something I'd say we ever gave much thought to.

(Although @adamchester probably gave it a lot more thought than I did :-) )

**Comment by adamchester** [comment]
I did give it some thought, but I couldn't come up with a better solution 👍

**Comment by 304NotModified** [comment]
thanks @nblumhardt !

Not sure if it's counter-intuitively :P

**Comment by nblumhardt** [comment]
In the end, it's really a malformed template, so relying on this as a consumer would be a bad idea either way :-)

**Comment by 304NotModified** [comment]
garbage in - garbage out ;)

**Comment by miyu** [comment]
Since it's a malformed template I'd expect an exception, not the logger to continue gracefully. In an ideal world (which we don't live in) this would be a compile-time error. If we want compatibility with other libraries to support this counterintuitive behavior, perhaps hide behind a flag and throw a descriptive exception otherwise? The tradeoff being you're no longer a configuration-less drop-in replacement.
