### ISSUE TITLE
Prepare parse / template syntax for Interpolated Strings

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.StructuredEvents#5]
e.g.

```
logger.LogInterpolated($"{car}");
```

nb: we can't use overloads, e.g. `log.Log`

We probable could support the `@` operator, but not the `$`?

See https://msdn.microsoft.com/en-us/library/dn961160.aspx

```
$ " <text> { <interpolation-expression> <optional-comma-field-width> <optional-colon-format> } <text> ... } "
```

https://msdn.microsoft.com/en-us/library/dn961160.aspx

**Comment by jods4** [comment]
I am not sure what you want to do here?
At runtime `$"{car}"` will be executed and result in a string, won't it? Unlike Javascript I don't think you can take part in the formatting process, except for the culture.

**Comment by 304NotModified** [comment]
> At runtime $"{car}" will be executed and result in a string,

Not if the parameter is a `FormattableString`. (and _no_ overload with `string`)

But I tested it, and it's not an improvement because we can't read the hole name. 

So this could work:

```
logger.Log($"{car:car1}); //name car1
logger.Log($"{car:@car1}); //name car1, @ operator
logger.Log($"{@car:car1});  //name car1, @ operator, option 2
```

and this won't work:

```
logger.Log($"{car}); //We have object car, but what about the name? Index 0?
```

So maybe this is a no-go

**Comment by 304NotModified** [comment]
See https://github.com/NLog/yamtp/tree/interpolated-strings

**Comment by jods4** [comment]
Thanks for reminding me this! I completely forgot about that obscure feature.
In my opinion it deserves to be better known because of `Invariant($"pi = {3.14}")`! 😃 

But I don't think it will help us much: you can't put @ or $ in the holes and you can't read the holes content at all.

Introducing the name in the format string is not standard for message templates and "eats" the format position. 

I am really not sure if it's worth pursuing this option.

**Comment by 304NotModified** [comment]
Won't fix as the compiler won't help us.
